### PR TITLE
String man

### PR DESCRIPTION
**Pull request by mitchellblom**
@blairvansant Enter works to execute, but not button. Any suggestions?

### CODE REVIEW

**Comment by OwenHerndon** [comment]
Nice job on keystroke entry or button click.

A thing to consider would be to clear out the input field upon button press/keystroke to ready for the next entry.

Also in your reverse function and alphabet function you are continuously writing to the dom without clearing out the previous entry/string. 
```
document.getElementById("rev").innerHTML += reverseString;
```
So we might want to add something above this that clears out "rev"
```
document.getElementById("rev").innerHTML = "";
```
However this clears out the whole id. A couple of solutions. One being changing the html an placing a empty div that has the id inside your p tags. So that your output is being written to an empty div that you keep changing back to empty before filling it again.

The other way would be to include the string  "Reversed: " to your output the function returns.

**Comment by mitchellblom** [comment]
@OwenHerndon great advice! edits have been made for each of your suggestions.

**Comment by OwenHerndon** [comment]
Nice job clearing out your elements. However you still have to delete the input field each test. We can fix that if you like.

First you need to target the function you use that calls your other functions. So lets look at adding a line to the 
```
function manipulateString(text) {
	reversal(text);
	alphabits(text);
	palindrome(text);
};
```
So after your invoke your three functions and logic is returned you want to clear out the input so another word can be tested. But now we are dealing with a input field not so we cant use the .innerHTML method like we used above. 

Instead we need .value

Something like this
```
document.getElementById("inputString").value = "";
```
But we've already declared this id above and stored it into a variable of input.
So another solution would be to add this line instead
```
input.value = "";
```
Give that a shot if you'd like. Everything else looks good, sound logic.
👍

**Comment by mitchellblom** [comment]
Played around with those input reset solutions and ended up going with ```input.value = ""```

**Pull request merged**
